controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
add_to_favorites:
    path: '/add-to-favorites/{id}'
    controller: 'App\Controller\RecipesController::addFavorite'
    methods: ['POST']
remove_from_favorites:
    path: '/remove-from-favorites/{id}'
    controller: 'App\Controller\RecipesController::removeFavorite'
    methods: ['DELETE']